FROM elixir:latest

RUN apt-get update && \
	curl -sL https://deb.nodesource.com/setup_10.x | bash && \
	apt-get install -y --no-install-recommends build-essential nodejs inotify-tools && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN mix local.hex --force && \
	mix local.rebar --force && \
	mix archive.install --force hex phx_new 1.4.2
